# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

load("//bazel:otel_cc.bzl", "otel_cc_binary_combo")

# otel_cc_binary_combo(
#     name = "etw_threadpool",
#     srcs = [
#         "main.cc",
#     ],
#     tags = [
#         "etw",
#         "examples",
#     ],
#     deps = [
#         "//api",
#         "//exporters/etw:etw_exporter",
#         "//:windows_only",
#     ],
# )
