name: otel_sdk_git_infra
on:
  push:
    tags:
      - "*"
    branches:
      - main
jobs:
  otel_sdk_build:
    name: testing otel_sdk_git_infra
    runs-on: [self-hosted, Windows, X64]
    permissions:
      contents: write
    steps:
#      - run: winget upgrade bazelisk -h --accept-source-agreements --accept-package-agreements || winget install bazelisk -h --accept-source-agreements --accept-package-agreements || echo swallowing winget error
      - uses: actions/checkout@v4
      - run: bazelisk test -k --//:with_dll -- ...
